import { domify } from 'min-dom';

import { getBusinessObject } from 'bpmn-js/lib/util/ModelUtil';

import {
  getPermissions,
  subscribe,
  setManageSecretsHandler
} from './react/store';

import {
  openCreateOverlay,
  openEditOverlay,
  openXmlViewer,
  openTemplateViewer,
  createManageController
} from './react/mounts';

/**
 * Inline lucide icon markup (https://lucide.dev) for the vanilla toolbar
 * buttons. Sized to sit next to the 12px button labels; `currentColor`
 * inherits the button text colour.
 */
const LUCIDE_ATTRS =
  'xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" ' +
  'fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"';
const ICON_CODE = `<svg ${LUCIDE_ATTRS}><path d="m16 18 6-6-6-6"/><path d="m8 6-6 6 6 6"/></svg>`;
const ICON_BRACES = `<svg ${LUCIDE_ATTRS}><path d="M8 3H7a2 2 0 0 0-2 2v5a2 2 0 0 1-2 2 2 2 0 0 1 2 2v5c0 1.1.9 2 2 2h1"/><path d="M16 21h1a2 2 0 0 0 2-2v-5c0-1.1.9-2 2-2a2 2 0 0 1-2-2V5a2 2 0 0 0-2-2h-1"/></svg>`;

/**
 * Mounts the demo toolbar: the "Manage" modal (Hub simulation) and the XML /
 * template viewers. The modal layer is implemented in React (`src/react/*`);
 * this module keeps the vanilla glue that integrates with the bpmn-js
 * properties panel (chooser interception and permission styling), which lives
 * in the Preact-rendered properties panel and is reached through the DOM.
 *
 * Note: the underlying modeler service is still named `connectionInstances`,
 * and the chooser DOM still uses `bio-properties-panel-connection-chooser*`
 * classes/labels. These are internal implementation handles in the upstream
 * `bpmn-js-element-templates` `connections-design` branch; only the data
 * contract (`configuration*` fields and `modelerConfiguration*` attributes)
 * was renamed.
 */
export function mountCredentialsUI(modeler, container, elementTemplates = []) {
  const credentialInstances = modeler.get('connectionInstances', false);
  const bpmnjs = modeler.get('bpmnjs');

  const toolbar = domify('<div class="ci-toolbar"></div>');
  container.appendChild(toolbar);

  if (credentialInstances) {
    const manage = createManageController(credentialInstances);

    // Let secret fields deep-link to the Secrets tab.
    setManageSecretsHandler((tab) => manage.open(tab));

    mountManageButton(manage, toolbar);
    wireChooserCreateButton(modeler, credentialInstances, elementTemplates);
    wireChooserUpdateButton(modeler, credentialInstances, elementTemplates);
    wireChooserPermissionStyles();

    // Keep the chooser action styles in sync when permissions change in the store.
    subscribe(() => refreshChooserPermissionStyles());
  }

  mountXmlViewer(bpmnjs, toolbar);
  mountTemplateViewer(modeler, toolbar, elementTemplates);
}

function mountManageButton(manage, toolbar) {
  const toggleBtn = domify('<button class="ci-toggle-btn">Manage Credentials and Secrets</button>');
  toolbar.appendChild(toggleBtn);
  toggleBtn.addEventListener('click', () => manage.open('credentials'));
}

/**
 * Build a map of properties-panel entry id → { configurationTemplate, property } for every
 * `Configuration` property across the element templates. The entry id is generated by
 * the upstream provider as `custom-entry-${templateId}-${index}` (see
 * custom-properties/index.js), where `templateId` is `${template.id}-${groupId}`
 * for grouped properties or `${template.id}` for ungrouped ones, and `index` is the
 * property's position within its group. We replicate that here so the "Create
 * connection" button can resolve which template/binding the chooser belongs to.
 */
function buildConfigurationPropertyMap(elementTemplates) {
  const map = {};

  const register = (entryId, property) => {
    if (property.type === 'Configuration') {
      const configurationTemplate = property.configurationTemplate;
      if (configurationTemplate) {
        map[entryId] = { configurationTemplate, property };
      }
    }
  };

  (elementTemplates || []).forEach(template => {
    const properties = template.properties || [];
    const groups = template.groups || [];

    // group properties by group id, preserving first-occurrence order
    const grouped = {};
    const order = [];
    properties.forEach(p => {
      const key = p.group === undefined ? 'undefined' : p.group;
      if (!grouped[key]) {
        grouped[key] = [];
        order.push(key);
      }
      grouped[key].push(p);
    });

    const defaultProps = [];
    order.forEach(key => {
      const groupDef = groups.find(g => g.id === key);
      if (!groupDef) {
        defaultProps.push(...grouped[key]);
        return;
      }
      const templateId = `${ template.id }-${ key }`;
      grouped[key].forEach((property, index) => {
        register(`custom-entry-${ templateId }-${ index }`, property);
      });
    });

    defaultProps.forEach((property, index) => {
      register(`custom-entry-${ template.id }-${ index }`, property);
    });
  });

  return map;
}

/**
 * Fallback resolver: find the `Configuration` property + templateRef from the
 * element's applied element template (used if the entry id lookup misses).
 */
function resolveConfigurationPropertyFromElement(element, elementTemplates) {
  const bo = getBusinessObject(element);
  const templateId = bo && bo.get && bo.get('zeebe:modelerTemplate');

  if (!templateId) {
    return undefined;
  }

  const template = (elementTemplates || []).find(t => t.id === templateId);
  if (!template) {
    return undefined;
  }

  const configurationProps = (template.properties || []).filter(p => p.type === 'Configuration');

  // Only safe to auto-resolve when there is exactly one configuration property
  if (configurationProps.length !== 1) {
    return undefined;
  }

  const property = configurationProps[0];
  const configurationTemplate = property.configurationTemplate;

  return configurationTemplate ? { configurationTemplate, property } : undefined;
}

const GO_TO_LABEL = 'Go to connection';
const UPDATE_LABEL = 'Update connection';

/**
 * Relabels "Go to connection" → "Update connection" and visually disables the
 * "Create connection" / "Update connection" chooser actions when the matching
 * permission is missing. Re-runs as the properties panel re-renders and whenever
 * permissions change (see `refreshChooserPermissionStyles`).
 */
function applyChooserPermissionStyles(root) {
  const permissions = getPermissions();

  // Relabel the context-menu item, then reflect update permission
  root.querySelectorAll('.bio-properties-panel-connection-chooser-context-menu-item').forEach(item => {
    if (item.textContent.trim() === GO_TO_LABEL) {
      item.textContent = UPDATE_LABEL;
    }
    if (item.textContent.trim() === UPDATE_LABEL) {
      setChooserActionDisabled(
        item,
        !permissions.update,
        'You don’t have permission to update connections on this cluster. Ask your cluster admin.'
      );
    }
  });

  // Reflect create permission on the "Create connection" buttons
  root.querySelectorAll('.bio-properties-panel-connection-chooser-create').forEach(btn => {
    setChooserActionDisabled(
      btn,
      !permissions.create,
      'You don’t have permission to create connections on this cluster. Ask your cluster admin.'
    );
  });
}

function setChooserActionDisabled(el, disabled, reason) {
  if (disabled) {
    el.classList.add('ci-perm-disabled');
    el.setAttribute('disabled', 'disabled');
    el.setAttribute('aria-disabled', 'true');
    el.setAttribute('title', reason);
    ensurePermissionReason(el, reason);
  } else {
    el.classList.remove('ci-perm-disabled');
    el.removeAttribute('disabled');
    el.removeAttribute('aria-disabled');
    if (el.getAttribute('title') === reason) {
      el.removeAttribute('title');
    }
    removePermissionReason(el);
  }
}

/**
 * Render an always-visible inline explanation directly after a disabled chooser
 * action so the user understands *why* it is disabled. A hover-only `title` is
 * not enough here — the disabled control has `pointer-events: none`, so its
 * native tooltip never shows. Idempotent: safe to call repeatedly from the
 * MutationObserver without re-inserting or looping.
 */
function ensurePermissionReason(el, reason) {
  const next = el.nextElementSibling;

  if (next && next.classList.contains('ci-perm-reason')) {
    const text = next.querySelector('.ci-perm-reason-text');
    if (text && text.textContent !== reason) {
      text.textContent = reason;
    }
    return;
  }

  const node = domify(
    '<div class="ci-perm-reason" role="note">' +
      '<svg class="ci-perm-reason-icon" width="14" height="14" viewBox="0 0 16 16" aria-hidden="true">' +
        '<circle cx="8" cy="8" r="7" fill="none" stroke="currentColor" stroke-width="1.5" />' +
        '<rect x="7.25" y="7" width="1.5" height="4.5" rx="0.75" fill="currentColor" />' +
        '<circle cx="8" cy="4.6" r="0.95" fill="currentColor" />' +
      '</svg>' +
      '<span class="ci-perm-reason-text"></span>' +
    '</div>'
  );

  node.querySelector('.ci-perm-reason-text').textContent = reason;
  el.insertAdjacentElement('afterend', node);
}

function removePermissionReason(el) {
  const next = el.nextElementSibling;
  if (next && next.classList.contains('ci-perm-reason')) {
    next.remove();
  }
}

/**
 * Re-apply the permission styles across the whole document. Reassigned by
 * `wireChooserPermissionStyles` and called when the permission toggles change.
 */
let refreshChooserPermissionStyles = () => {};

/**
 * Observe the properties panel and keep the chooser action permission styles in
 * sync as it re-renders.
 */
function wireChooserPermissionStyles() {
  const refresh = () => applyChooserPermissionStyles(document);

  const observer = new MutationObserver(() => refresh());
  observer.observe(document.body, { childList: true, subtree: true });

  refreshChooserPermissionStyles = refresh;
  refresh();
}

/**
 * The upstream chooser's "Create connection" button only clears the selection
 * (`onSelect(null)`). Intercept it in the capture phase to open the prototype's
 * credential creation form instead, scoped to the chooser's credential template.
 * After creation the new credential is automatically applied to the element.
 */
function wireChooserCreateButton(modeler, credentialInstances, elementTemplates) {
  const propertyMap = buildConfigurationPropertyMap(elementTemplates);

  document.addEventListener('click', (event) => {
    const createBtn = event.target.closest('.bio-properties-panel-connection-chooser-create');

    if (!createBtn) {
      return;
    }

    if (!getPermissions().create) {
      return;
    }

    // Prevent the upstream handler (which clears the selection)
    event.preventDefault();
    event.stopPropagation();

    const chooser = createBtn.closest('.bio-properties-panel-connection-chooser');
    const entryId = chooser && chooser.getAttribute('data-entry-id');

    const element = modeler.get('selection').get()[0];

    let mapping = entryId ? propertyMap[entryId] : undefined;

    // Fall back to the element's applied template if the entry id lookup misses
    if (!mapping && element) {
      mapping = resolveConfigurationPropertyFromElement(element, elementTemplates);
    }

    openCreateOverlay(credentialInstances, mapping && mapping.configurationTemplate, (created) => {

      // Auto-apply the freshly created credential to the element
      if (element && mapping && mapping.property) {
        applyCredentialToElement(modeler, element, mapping.property, created);
      }
    });
  }, true);
}

/**
 * The upstream context menu offers a "Go to connection" item (a stub). We relabel
 * it to "Update connection" and intercept it to open the prototype's edit form
 * for the applied credential — but only when the user has update permission.
 */
function wireChooserUpdateButton(modeler, credentialInstances, elementTemplates) {
  const propertyMap = buildConfigurationPropertyMap(elementTemplates);

  // Intercept clicks on the (relabeled) update item
  document.addEventListener('click', (event) => {
    const item = event.target.closest('.bio-properties-panel-connection-chooser-context-menu-item');

    if (!item || item.textContent.trim() !== UPDATE_LABEL) {
      return;
    }

    // Prevent the upstream "Go to connection" handler
    event.preventDefault();
    event.stopPropagation();

    if (!getPermissions().update) {
      return;
    }

    const chooser = item.closest('.bio-properties-panel-connection-chooser');
    const entryId = chooser && chooser.getAttribute('data-entry-id');

    const element = modeler.get('selection').get()[0];

    let mapping = entryId ? propertyMap[entryId] : undefined;
    if (!mapping && element) {
      mapping = resolveConfigurationPropertyFromElement(element, elementTemplates);
    }

    if (!element || !mapping || !mapping.property) {
      return;
    }

    const applied = getAppliedCredential(modeler, element, mapping.property, credentialInstances);

    if (!applied) {
      return;
    }

    openEditOverlay(credentialInstances, applied.credential, applied.idx);
  }, true);
}

/**
 * Resolve the credential instance currently applied to an element's binding by
 * reading the `=camunda.vars.env.<NAME>` reference from the `zeebe:input`.
 */
function getAppliedCredential(modeler, element, property, credentialInstances) {
  if (!property.binding || property.binding.type !== 'zeebe:input') {
    return undefined;
  }

  const bo = getBusinessObject(element);
  const extensionElements = bo.get('extensionElements');
  if (!extensionElements) {
    return undefined;
  }

  const ioMapping = extensionElements.get('values').find(v => v.$type === 'zeebe:IoMapping');
  if (!ioMapping) {
    return undefined;
  }

  const input = ioMapping.get('inputParameters').find(p => p.target === property.binding.name);
  if (!input || !input.source) {
    return undefined;
  }

  const match = /camunda\.vars\.env\.([A-Z][A-Z0-9_]*)/.exec(input.source);
  const name = match && match[1];
  if (!name) {
    return undefined;
  }

  const all = credentialInstances.getAll();
  const idx = all.findIndex(c => c.name === name);
  if (idx === -1) {
    return undefined;
  }

  return { credential: all[idx], idx };
}

/**
 * Writes the credential reference (`=camunda.vars.env.<name>`) and the cached
 * credential metadata to the element's `zeebe:input` binding — mirroring what
 * the upstream chooser does when a credential is selected.
 */
function applyCredentialToElement(modeler, element, property, credential) {
  if (!property.binding || property.binding.type !== 'zeebe:input') {
    return;
  }

  const bpmnFactory = modeler.get('bpmnFactory');
  const modeling = modeler.get('modeling');

  const bo = getBusinessObject(element);
  const targetName = property.binding.name;
  const source = `=camunda.vars.env.${ credential.name }`;

  // Ensure extensionElements
  let extensionElements = bo.get('extensionElements');
  if (!extensionElements) {
    extensionElements = bpmnFactory.create('bpmn:ExtensionElements', { values: [] });
    extensionElements.$parent = bo;
    modeling.updateProperties(element, { extensionElements });
  }

  // Ensure zeebe:IoMapping
  let ioMapping = extensionElements.get('values').find(v => v.$type === 'zeebe:IoMapping');
  if (!ioMapping) {
    ioMapping = bpmnFactory.create('zeebe:IoMapping', { inputParameters: [], outputParameters: [] });
    ioMapping.$parent = extensionElements;
    modeling.updateModdleProperties(element, extensionElements, {
      values: [ ...extensionElements.get('values'), ioMapping ]
    });
  }

  // Ensure the zeebe:Input parameter
  let input = ioMapping.get('inputParameters').find(p => p.target === targetName);
  if (!input) {
    input = bpmnFactory.create('zeebe:Input', { target: targetName });
    input.$parent = ioMapping;
    modeling.updateModdleProperties(element, ioMapping, {
      inputParameters: [ ...ioMapping.get('inputParameters'), input ]
    });
  }

  // Set the FEEL reference and cached configuration metadata.
  // Design attribute names (singular, no version): modelerConfigurationTemplate / modelerConfigurationName.
  // The upstream chooser popover writes the same attributes when an existing instance is selected.
  modeling.updateModdleProperties(element, input, {
    source,
    modelerConfigurationTemplate: credential.configurationTemplate,
    modelerConfigurationName: credential.displayName || credential.name
  });
}

function mountXmlViewer(bpmnjs, toolbar) {
  const xmlBtn = domify(`<button class="ci-toggle-btn">${ICON_CODE}<span>XML</span></button>`);
  toolbar.appendChild(xmlBtn);

  xmlBtn.addEventListener('click', async () => {
    const { xml } = await bpmnjs.saveXML({ format: true });
    openXmlViewer(xml);
  });
}

/**
 * Demo viewer for the raw element template JSON. Shows the element template
 * applied to the currently selected element (the same JSON the connector author
 * ships) so all moving parts are visible; falls back to listing every loaded
 * template when nothing with an applied template is selected.
 */
function mountTemplateViewer(modeler, toolbar, elementTemplates) {
  const btn = domify(`<button class="ci-toggle-btn">${ICON_BRACES}<span>Template</span></button>`);
  toolbar.appendChild(btn);

  btn.addEventListener('click', () => {
    const element = modeler.get('selection').get()[0];

    let templates = [];
    let subtitle = '';

    if (element) {
      const bo = getBusinessObject(element);
      const templateId = bo && bo.get && bo.get('zeebe:modelerTemplate');
      const templateVersion = bo && bo.get && bo.get('zeebe:modelerTemplateVersion');

      if (templateId) {
        const applied =
          (elementTemplates || []).find(t => t.id === templateId && t.version === templateVersion) ||
          (elementTemplates || []).find(t => t.id === templateId);

        if (applied) {
          templates = [ applied ];
          subtitle = `Applied to ${ element.id } · ${ applied.name } (v${ applied.version })`;
        }
      }
    }

    if (!templates.length) {
      templates = elementTemplates || [];
      subtitle = element && element.id
        ? `${ element.id } has no applied element template — showing all ${ templates.length } loaded template(s)`
        : `No element selected — showing all ${ templates.length } loaded template(s)`;
    }

    const json = JSON.stringify(templates.length === 1 ? templates[0] : templates, null, 2);

    openTemplateViewer(json, subtitle);
  });
}
