import { domify } from 'min-dom';

import { getBusinessObject } from 'bpmn-js/lib/util/ModelUtil';

import {
  SLACK_ICON,
  SAMPLE_CREDENTIALS,
  CREDENTIAL_TEMPLATES
} from './sample-credentials';

function escapeHTML(unsafe) {
  return unsafe
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

/**
 * Derive UPPER_SNAKE_CASE credential ID from a display name.
 * e.g. "My Slack workspace" → "MY_SLACK_WORKSPACE"
 */
function toUpperSnakeCase(displayName) {
  return displayName
    .trim()
    .replace(/[^a-zA-Z0-9\s_]/g, '')
    .replace(/\s+/g, '_')
    .toUpperCase();
}

/**
 * Mounts the demo toolbar: the "Credentials" modal (Hub simulation) and the
 * XML viewer. Mirrors the prototype UI from bpmn-js-element-templates.
 *
 * Note: the underlying modeler service is still named `connectionInstances`
 * because it is provided by the upstream `bpmn-js-element-templates`
 * `connections-design` branch, which has not been renamed yet.
 */
export function mountCredentialsUI(modeler, container, elementTemplates = []) {
  const credentialInstances = modeler.get('connectionInstances', false);
  const bpmnjs = modeler.get('bpmnjs');

  if (credentialInstances) {
    mountCredentialsModal(credentialInstances, container);
    wireChooserCreateButton(modeler, credentialInstances, elementTemplates);
    wireChooserUpdateButton(modeler, credentialInstances, elementTemplates);
    wireChooserPermissionStyles();
  }

  mountXmlViewer(bpmnjs, container);
}

/**
 * Build a map of properties-panel entry id → { templateRef, property } for every
 * `Credential` property across the element templates. The entry id is generated by
 * the upstream provider as `custom-entry-${templateId}-${index}` (see
 * custom-properties/index.js), where `templateId` is `${template.id}-${groupId}`
 * for grouped properties or `${template.id}` for ungrouped ones, and `index` is the
 * property's position within its group. We replicate that here so the "Create
 * connection" button can resolve which template/binding the chooser belongs to.
 */
function buildCredentialPropertyMap(elementTemplates) {
  const map = {};

  const register = (entryId, property) => {
    if (property.type === 'Credential') {
      const templateRef = property.credentialTemplate || property.schemaRef;
      if (templateRef) {
        map[entryId] = { templateRef, property };
      }
    }
  };

  (elementTemplates || []).forEach(template => {
    const properties = template.properties || [];
    const groups = template.groups || [];

    // group properties by group id, preserving first-occurrence order
    const grouped = {};
    const order = [];
    properties.forEach(p => {
      const key = p.group === undefined ? 'undefined' : p.group;
      if (!grouped[key]) {
        grouped[key] = [];
        order.push(key);
      }
      grouped[key].push(p);
    });

    const defaultProps = [];
    order.forEach(key => {
      const groupDef = groups.find(g => g.id === key);
      if (!groupDef) {
        defaultProps.push(...grouped[key]);
        return;
      }
      const templateId = `${ template.id }-${ key }`;
      grouped[key].forEach((property, index) => {
        register(`custom-entry-${ templateId }-${ index }`, property);
      });
    });

    defaultProps.forEach((property, index) => {
      register(`custom-entry-${ template.id }-${ index }`, property);
    });
  });

  return map;
}

/**
 * Fallback resolver: find the `Credential` property + templateRef from the
 * element's applied element template (used if the entry id lookup misses).
 */
function resolveCredentialPropertyFromElement(element, elementTemplates) {
  const bo = getBusinessObject(element);
  const templateId = bo && bo.get && bo.get('zeebe:modelerTemplate');

  if (!templateId) {
    return undefined;
  }

  const template = (elementTemplates || []).find(t => t.id === templateId);
  if (!template) {
    return undefined;
  }

  const credentialProps = (template.properties || []).filter(p => p.type === 'Credential');

  // Only safe to auto-resolve when there is exactly one credential property
  if (credentialProps.length !== 1) {
    return undefined;
  }

  const property = credentialProps[0];
  const templateRef = property.credentialTemplate || property.schemaRef;

  return templateRef ? { templateRef, property } : undefined;
}

const GO_TO_LABEL = 'Go to connection';
const UPDATE_LABEL = 'Update connection';

/**
 * Relabels "Go to connection" → "Update connection" and visually disables the
 * "Create connection" / "Update connection" chooser actions when the matching
 * permission is missing. Re-runs as the properties panel re-renders and whenever
 * permissions change (see `refreshChooserPermissionStyles`).
 */
function applyChooserPermissionStyles(root) {
  // Relabel the context-menu item, then reflect update permission
  root.querySelectorAll('.bio-properties-panel-connection-chooser-context-menu-item').forEach(item => {
    if (item.textContent.trim() === GO_TO_LABEL) {
      item.textContent = UPDATE_LABEL;
    }
    if (item.textContent.trim() === UPDATE_LABEL) {
      setChooserActionDisabled(
        item,
        !permissions.update,
        'You do not have permission to update this connection.'
      );
    }
  });

  // Reflect create permission on the "Create connection" buttons
  root.querySelectorAll('.bio-properties-panel-connection-chooser-create').forEach(btn => {
    setChooserActionDisabled(
      btn,
      !permissions.create,
      'You do not have permission to create a connection.'
    );
  });
}

function setChooserActionDisabled(el, disabled, title) {
  if (disabled) {
    el.classList.add('ci-perm-disabled');
    el.setAttribute('disabled', 'disabled');
    el.setAttribute('aria-disabled', 'true');
    el.setAttribute('title', title);
  } else {
    el.classList.remove('ci-perm-disabled');
    el.removeAttribute('disabled');
    el.removeAttribute('aria-disabled');
    if (el.getAttribute('title') === title) {
      el.removeAttribute('title');
    }
  }
}

/**
 * Re-apply the permission styles across the whole document. Reassigned by
 * `wireChooserPermissionStyles` and called when the permission toggles change.
 */
let refreshChooserPermissionStyles = () => {};

/**
 * Observe the properties panel and keep the chooser action permission styles in
 * sync as it re-renders.
 */
function wireChooserPermissionStyles() {
  const refresh = () => applyChooserPermissionStyles(document);

  const observer = new MutationObserver(() => refresh());
  observer.observe(document.body, { childList: true, subtree: true });

  refreshChooserPermissionStyles = refresh;
  refresh();
}

/**
 * The upstream chooser's "Create connection" button only clears the selection
 * (`onSelect(null)`). Intercept it in the capture phase to open the prototype's
 * credential creation form instead, scoped to the chooser's credential template.
 * After creation the new credential is automatically applied to the element.
 */
function wireChooserCreateButton(modeler, credentialInstances, elementTemplates) {
  const propertyMap = buildCredentialPropertyMap(elementTemplates);

  document.addEventListener('click', (event) => {
    const createBtn = event.target.closest('.bio-properties-panel-connection-chooser-create');

    if (!createBtn) {
      return;
    }

    if (!permissions.create) {
      return;
    }

    // Prevent the upstream handler (which clears the selection)
    event.preventDefault();
    event.stopPropagation();

    const chooser = createBtn.closest('.bio-properties-panel-connection-chooser');
    const entryId = chooser && chooser.getAttribute('data-entry-id');

    const element = modeler.get('selection').get()[0];

    let mapping = entryId ? propertyMap[entryId] : undefined;

    // Fall back to the element's applied template if the entry id lookup misses
    if (!mapping && element) {
      mapping = resolveCredentialPropertyFromElement(element, elementTemplates);
    }

    openCreateOverlay(credentialInstances, mapping && mapping.templateRef, (created) => {

      // Auto-apply the freshly created credential to the element
      if (element && mapping && mapping.property) {
        applyCredentialToElement(modeler, element, mapping.property, created);
      }
    });
  }, true);
}

/**
 * The upstream context menu offers a "Go to connection" item (a stub). We relabel
 * it to "Update connection" and intercept it to open the prototype's edit form
 * for the applied credential — but only when the user has update permission.
 */
function wireChooserUpdateButton(modeler, credentialInstances, elementTemplates) {
  const propertyMap = buildCredentialPropertyMap(elementTemplates);

  // Intercept clicks on the (relabeled) update item
  document.addEventListener('click', (event) => {
    const item = event.target.closest('.bio-properties-panel-connection-chooser-context-menu-item');

    if (!item || item.textContent.trim() !== UPDATE_LABEL) {
      return;
    }

    // Prevent the upstream "Go to connection" handler
    event.preventDefault();
    event.stopPropagation();

    if (!permissions.update) {
      return;
    }

    const chooser = item.closest('.bio-properties-panel-connection-chooser');
    const entryId = chooser && chooser.getAttribute('data-entry-id');

    const element = modeler.get('selection').get()[0];

    let mapping = entryId ? propertyMap[entryId] : undefined;
    if (!mapping && element) {
      mapping = resolveCredentialPropertyFromElement(element, elementTemplates);
    }

    if (!element || !mapping || !mapping.property) {
      return;
    }

    const applied = getAppliedCredential(modeler, element, mapping.property, credentialInstances);

    if (!applied) {
      return;
    }

    openEditOverlay(credentialInstances, applied.credential, applied.idx);
  }, true);
}

/**
 * Resolve the credential instance currently applied to an element's binding by
 * reading the `=camunda.vars.env.<NAME>` reference from the `zeebe:input`.
 */
function getAppliedCredential(modeler, element, property, credentialInstances) {
  if (!property.binding || property.binding.type !== 'zeebe:input') {
    return undefined;
  }

  const bo = getBusinessObject(element);
  const extensionElements = bo.get('extensionElements');
  if (!extensionElements) {
    return undefined;
  }

  const ioMapping = extensionElements.get('values').find(v => v.$type === 'zeebe:IoMapping');
  if (!ioMapping) {
    return undefined;
  }

  const input = ioMapping.get('inputParameters').find(p => p.target === property.binding.name);
  if (!input || !input.source) {
    return undefined;
  }

  const match = /camunda\.vars\.env\.([A-Z][A-Z0-9_]*)/.exec(input.source);
  const name = match && match[1];
  if (!name) {
    return undefined;
  }

  const all = credentialInstances.getAll();
  const idx = all.findIndex(c => c.name === name);
  if (idx === -1) {
    return undefined;
  }

  return { credential: all[idx], idx };
}

/**
 * Writes the credential reference (`=camunda.vars.env.<name>`) and the cached
 * credential metadata to the element's `zeebe:input` binding — mirroring what
 * the upstream chooser does when a credential is selected.
 */
function applyCredentialToElement(modeler, element, property, credential) {
  if (!property.binding || property.binding.type !== 'zeebe:input') {
    return;
  }

  const bpmnFactory = modeler.get('bpmnFactory');
  const modeling = modeler.get('modeling');

  const bo = getBusinessObject(element);
  const targetName = property.binding.name;
  const source = `=camunda.vars.env.${ credential.name }`;

  // Ensure extensionElements
  let extensionElements = bo.get('extensionElements');
  if (!extensionElements) {
    extensionElements = bpmnFactory.create('bpmn:ExtensionElements', { values: [] });
    extensionElements.$parent = bo;
    modeling.updateProperties(element, { extensionElements });
  }

  // Ensure zeebe:IoMapping
  let ioMapping = extensionElements.get('values').find(v => v.$type === 'zeebe:IoMapping');
  if (!ioMapping) {
    ioMapping = bpmnFactory.create('zeebe:IoMapping', { inputParameters: [], outputParameters: [] });
    ioMapping.$parent = extensionElements;
    modeling.updateModdleProperties(element, extensionElements, {
      values: [ ...extensionElements.get('values'), ioMapping ]
    });
  }

  // Ensure the zeebe:Input parameter
  let input = ioMapping.get('inputParameters').find(p => p.target === targetName);
  if (!input) {
    input = bpmnFactory.create('zeebe:Input', { target: targetName });
    input.$parent = ioMapping;
    modeling.updateModdleProperties(element, ioMapping, {
      inputParameters: [ ...ioMapping.get('inputParameters'), input ]
    });
  }

  // Set the FEEL reference and cached credential metadata
  modeling.updateModdleProperties(element, input, {
    source,
    modelerCredentialsTemplate: credential.templateRef || credential.credentialTemplate,
    modelerCredentialsName: credential.displayName || credential.name,
    modelerCredentialsVersion: credential.version
  });
}

/**
 * Opens the credential creation form in a standalone modal overlay.
 * @param {Function} [onCreated] - called with the created credential after save
 */
function openCreateOverlay(credentialInstances, templateId, onCreated) {
  const backdrop = domify('<div class="ci-modal-backdrop"></div>');
  const modal = domify('<div class="ci-modal"></div>');
  modal.innerHTML = `
    <div class="ci-modal-header">
      <h3>Create credential</h3>
      <button data-close>&times;</button>
    </div>
    <div class="ci-modal-body">
      <div class="ci-form-container"></div>
    </div>
  `;
  backdrop.appendChild(modal);
  document.body.appendChild(backdrop);

  const close = () => backdrop.remove();

  backdrop.addEventListener('click', (e) => {
    if (e.target === backdrop) close();
  });
  modal.querySelector('[data-close]').addEventListener('click', close);

  const formContainer = modal.querySelector('.ci-form-container');
  renderCreateForm(formContainer, credentialInstances, (created) => {
    close();
    if (created && onCreated) {
      onCreated(created);
    }
  }, templateId);
}

/**
 * Opens the credential edit form in a standalone modal overlay, pre-filled with
 * the applied credential's values.
 */
function openEditOverlay(credentialInstances, credential, idx) {
  const backdrop = domify('<div class="ci-modal-backdrop"></div>');
  const modal = domify('<div class="ci-modal"></div>');
  modal.innerHTML = `
    <div class="ci-modal-header">
      <h3>Update credential</h3>
      <button data-close>&times;</button>
    </div>
    <div class="ci-modal-body">
      <div class="ci-form-container"></div>
    </div>
  `;
  backdrop.appendChild(modal);
  document.body.appendChild(backdrop);

  const close = () => backdrop.remove();

  backdrop.addEventListener('click', (e) => {
    if (e.target === backdrop) close();
  });
  modal.querySelector('[data-close]').addEventListener('click', close);

  const formContainer = modal.querySelector('.ci-form-container');
  renderEditForm(formContainer, credential, idx, credentialInstances, close, false);
}

/**
 * Simulated permission state. In production this comes from
 * GET /v2/user/cluster-variable-permissions (see GAP-002).
 */
const permissions = {
  create: true,
  update: true
};

function mountCredentialsModal(credentialInstances, container) {
  const toggleBtn = domify('<button class="ci-toggle-btn">Credentials</button>');
  container.appendChild(toggleBtn);

  let backdrop = null;

  const closeModal = () => {
    if (backdrop) {
      backdrop.remove();
      backdrop = null;
    }
  };

  const openModal = () => {
    if (backdrop) return;

    backdrop = domify('<div class="ci-modal-backdrop"></div>');
    const modal = domify('<div class="ci-modal"></div>');
    backdrop.appendChild(modal);
    document.body.appendChild(backdrop);

    backdrop.addEventListener('click', (e) => {
      if (e.target === backdrop) closeModal();
    });

    renderModal(modal);
  };

  const renderModal = (modal) => {
    const all = credentialInstances.getAll();
    const loaded = credentialInstances.isLoaded();

    modal.innerHTML = `
      <div class="ci-modal-header">
        <h3>Credential Instances (Hub simulation)</h3>
        <button data-close>&times;</button>
      </div>
      <div class="ci-modal-body">
        <div class="ci-section">
          <h4>Permissions (simulated)</h4>
          <div class="ci-permissions">
            <label><input type="checkbox" data-perm="create" ${ permissions.create ? 'checked' : '' } /> create</label>
            <label><input type="checkbox" data-perm="update" ${ permissions.update ? 'checked' : '' } /> update</label>
          </div>
        </div>
        <div class="ci-section">
          <h4>Existing instances${ loaded ? '' : ' (not loaded — cluster disconnected)' }</h4>
          <div class="ci-list-container"></div>
        </div>
        ${ permissions.create ? `
        <div class="ci-section">
          <h4>Create new credential</h4>
          <div class="ci-create-actions">
            <button data-action="random">Create random (Slack)</button>
            <button data-action="explicit">Create from template…</button>
          </div>
          <div class="ci-form-container"></div>
        </div>
        ` : `
        <div class="ci-section">
          <p class="ci-empty">Creation disabled — user lacks <code>create</code> permission on this cluster.</p>
        </div>
        ` }
        <div class="ci-section">
          <h4>Bulk actions</h4>
          <div class="ci-create-actions">
            <button data-action="load-samples">Load samples</button>
            <button data-action="mark-loaded">Mark loaded (empty)</button>
          </div>
        </div>
      </div>
    `;

    modal.querySelector('[data-close]').addEventListener('click', closeModal);

    // Permission toggles
    modal.querySelectorAll('[data-perm]').forEach(cb => {
      cb.addEventListener('change', (e) => {
        permissions[e.target.dataset.perm] = e.target.checked;
        refreshChooserPermissionStyles();
        renderModal(modal);
      });
    });

    // Render instance list
    const listContainer = modal.querySelector('.ci-list-container');

    if (all.length === 0) {
      listContainer.innerHTML = '<p class="ci-empty">No credential instances available.</p>';
    } else {
      const list = domify('<ul class="ci-instance-list"></ul>');

      all.forEach((inst, idx) => {
        // Determine floor from matching credential template (if available)
        const matchingTemplate = CREDENTIAL_TEMPLATES.find(t => t.id === inst.credentialTemplate);
        const floor = matchingTemplate ? matchingTemplate.version : null;
        const isIncompatible = floor != null && inst.credentialTemplateVersion != null && inst.credentialTemplateVersion < floor;

        const li = domify(
          `<li class="${ isIncompatible ? 'ci-incompatible' : '' }">
            <div class="ci-inst-info">
              <span class="ci-inst-name">${ escapeHTML(inst.displayName || inst.name) }</span>
              <span class="ci-inst-meta">
                ${ escapeHTML(inst.credentialTemplate) } v${ inst.credentialTemplateVersion || '?' }
                ${ isIncompatible ? `<span class="ci-warning">⚠ Requires v${ floor }+</span>` : '' }
              </span>
            </div>
            <div class="ci-inst-actions">
              ${ permissions.update && isIncompatible ? `<button data-upgrade="${ idx }">Upgrade</button>` : '' }
              ${ permissions.update && !isIncompatible ? `<button data-edit="${ idx }">Edit</button>` : '' }
              <button data-remove="${ idx }">Remove</button>
            </div>
          </li>`
        );

        li.querySelector('[data-remove]').addEventListener('click', () => {
          const updated = credentialInstances.getAll().filter((_, i) => i !== idx);
          credentialInstances.setInstances(updated);
          renderModal(modal);
        });

        const editBtn = li.querySelector('[data-edit]');
        if (editBtn) {
          editBtn.addEventListener('click', () => {
            const formContainer = modal.querySelector('.ci-form-container');
            if (formContainer) {
              renderEditForm(formContainer, inst, idx, credentialInstances, () => renderModal(modal), false);
            }
          });
        }

        const upgradeBtn = li.querySelector('[data-upgrade]');
        if (upgradeBtn) {
          upgradeBtn.addEventListener('click', () => {
            const formContainer = modal.querySelector('.ci-form-container');
            if (formContainer) {
              renderEditForm(formContainer, inst, idx, credentialInstances, () => renderModal(modal), true);
            }
          });
        }

        list.appendChild(li);
      });

      listContainer.appendChild(list);
    }

    // Random creation
    if (permissions.create) {
      modal.querySelector('[data-action="random"]').addEventListener('click', () => {
        const id = Math.random().toString(36).slice(2, 7).toUpperCase();
        const current = credentialInstances.getAll();

        credentialInstances.setInstances([
          ...current,
          {
            name: 'SLACK_' + id,
            displayName: 'Slack ' + id.charAt(0) + id.slice(1).toLowerCase(),
            kind: 'CREDENTIAL',
            credentialTemplate: 'io.camunda:slack-credential:1',
            templateRef: 'io.camunda:slack-credential:1',
            credentialTemplateVersion: 2,
            version: 2,
            icon: SLACK_ICON
          }
        ]);

        renderModal(modal);
      });

      // Explicit creation — render credential template form
      const formContainer = modal.querySelector('.ci-form-container');

      modal.querySelector('[data-action="explicit"]').addEventListener('click', () => {
        renderCreateForm(formContainer, credentialInstances, () => renderModal(modal));
      });
    }

    // Bulk actions
    modal.querySelector('[data-action="load-samples"]').addEventListener('click', () => {
      credentialInstances.setInstances([ ...SAMPLE_CREDENTIALS ]);
      renderModal(modal);
    });

    modal.querySelector('[data-action="mark-loaded"]').addEventListener('click', () => {
      credentialInstances.setInstances([]);
      renderModal(modal);
    });
  };

  toggleBtn.addEventListener('click', openModal);
}

/**
 * Renders the creation form inside the given container.
 * @param {string} [templateId] - id of the credential template to create from
 */
function renderCreateForm(formContainer, credentialInstances, rerender, templateId) {
  const template = templateId
    ? CREDENTIAL_TEMPLATES.find(t => t.id === templateId)
    : CREDENTIAL_TEMPLATES[0];

  formContainer.innerHTML = '';

  const templateOptions = CREDENTIAL_TEMPLATES.map(t =>
    `<option value="${ escapeHTML(t.id) }" ${ t.id === template.id ? 'selected' : '' }>${ escapeHTML(t.name) }</option>`
  ).join('');

  const form = domify(
    `<div class="ci-form">
      <h5>Create new credential</h5>
      <div class="ci-form-row">
        <label>Credential template</label>
        <select data-field="template">${ templateOptions }</select>
      </div>
      <div class="ci-form-row">
        <label>Display name</label>
        <input type="text" data-field="displayName" placeholder="e.g. My Slack Workspace" />
      </div>
      <div class="ci-form-row">
        <label>Credential ID <span style="font-size:11px;color:#888;">(auto-suggested, immutable after creation)</span></label>
        <input type="text" data-field="name" placeholder="e.g. MY_SLACK_WORKSPACE" />
        <span class="ci-field-error" data-error="name"></span>
      </div>
      <div class="ci-form-row">
        <label>Version (stamped from template)</label>
        <label style="display:inline-flex;align-items:center;gap:4px;font-weight:normal;font-size:11px;color:#888;margin-bottom:4px;">
          <input type="checkbox" data-field="overrideVersion" />
          Override version (demo only — simulate outdated instances)
        </label>
        <input type="number" data-field="version" value="${ template.version }" min="1" disabled />
      </div>
      <hr/>
      <p style="font-size:11px;color:#666;margin:4px 0 8px;">
        Credential template properties (stored as cluster variable value)
      </p>
      ${ template.properties.map(p =>
        `<div class="ci-form-row">
          <label>${ escapeHTML(p.label) }${ p.required ? ' *' : '' }${ p.secret ? ' 🔒' : '' }</label>
          <input type="${ p.secret ? 'password' : 'text' }" data-prop="${ escapeHTML(p.key) }" placeholder="${ p.secret ? 'camunda.secrets.MY_SECRET' : escapeHTML(p.key) }" />
          ${ p.secret ? '<span class="ci-field-warning" data-secret-warning="' + escapeHTML(p.key) + '"></span>' : '' }
        </div>`
      ).join('') }
      <div class="ci-form-actions">
        <button data-primary data-action="submit">Create credential</button>
        <button data-action="cancel">Cancel</button>
      </div>
    </div>`
  );

  // Re-render when the template selection changes
  form.querySelector('[data-field="template"]').addEventListener('change', (e) => {
    renderCreateForm(formContainer, credentialInstances, rerender, e.target.value);
  });

  // Auto-suggest credential ID from display name
  const displayNameInput = form.querySelector('[data-field="displayName"]');
  const nameInput = form.querySelector('[data-field="name"]');
  let nameManuallyEdited = false;

  nameInput.addEventListener('input', () => {
    nameManuallyEdited = nameInput.value.trim() !== '';
  });

  displayNameInput.addEventListener('input', () => {
    if (!nameManuallyEdited || nameInput.value.trim() === '') {
      nameInput.value = toUpperSnakeCase(displayNameInput.value);
      nameManuallyEdited = false;
    }
  });

  // Toggle version override
  form.querySelector('[data-field="overrideVersion"]').addEventListener('change', (e) => {
    form.querySelector('[data-field="version"]').disabled = !e.target.checked;
  });

  form.querySelector('[data-action="cancel"]').addEventListener('click', () => {
    formContainer.innerHTML = '';
  });

  form.querySelector('[data-action="submit"]').addEventListener('click', () => {
    const name = nameInput.value.trim();
    const displayName = displayNameInput.value.trim();
    const version = parseInt(form.querySelector('[data-field="version"]').value, 10) || 1;
    const errorEl = form.querySelector('[data-error="name"]');

    errorEl.textContent = '';

    if (!name) {
      errorEl.textContent = 'Credential ID is required.';
      return;
    }

    if (!/^[A-Z][A-Z0-9_]*$/.test(name)) {
      errorEl.textContent = 'Must be UPPER_SNAKE_CASE (e.g. SLACK_PRODUCTION).';
      return;
    }

    // Name conflict check
    const existing = credentialInstances.getAll();
    if (existing.some(inst => inst.name === name)) {
      errorEl.textContent = 'A credential with this ID already exists. Choose a different ID.';
      return;
    }

    // Secret existence warnings (simulated — always warn for demo)
    template.properties.filter(p => p.secret).forEach(p => {
      const input = form.querySelector(`[data-prop="${ p.key }"]`);
      const warningEl = form.querySelector(`[data-secret-warning="${ p.key }"]`);
      if (input && warningEl && input.value.startsWith('camunda.secrets.')) {
        const secretName = input.value.slice('camunda.secrets.'.length);
        warningEl.textContent = `⚠ Secret "${ secretName }" cannot be verified (non-revealing API unavailable — GAP-003).`;
      }
    });

    // Collect the cluster-variable value from the template properties
    const storedValue = {};
    template.properties.forEach(p => {
      const input = form.querySelector(`[data-prop="${ p.key }"]`);
      if (input && input.value.trim() !== '') {
        storedValue[p.key] = input.value;
      }
    });

    credentialInstances.setInstances([
      ...existing,
      {
        name,
        displayName: displayName || name,
        kind: 'CREDENTIAL',
        credentialTemplate: template.id,
        templateRef: template.id,
        credentialTemplateVersion: version,
        version,
        storedValue,
        icon: template.icon
      }
    ]);

    formContainer.innerHTML = '';
    rerender({
      name,
      displayName: displayName || name,
      credentialTemplate: template.id,
      templateRef: template.id,
      credentialTemplateVersion: version,
      version
    });
  });

  formContainer.appendChild(form);
}

/**
 * Renders the edit/upgrade form for an existing credential.
 * @param {boolean} isUpgrade - true if this is a version upgrade (version < floor)
 */
function renderEditForm(formContainer, credential, idx, credentialInstances, rerender, isUpgrade) {
  const matchingTemplate = CREDENTIAL_TEMPLATES.find(t => t.id === credential.credentialTemplate);

  if (!matchingTemplate) {
    formContainer.innerHTML = '<p class="ci-empty">No matching credential template found for editing.</p>';
    return;
  }

  formContainer.innerHTML = '';

  const floor = matchingTemplate.version;
  const heading = isUpgrade
    ? `Upgrade "${ escapeHTML(credential.displayName || credential.name) }" — v${ credential.credentialTemplateVersion } → v${ floor }`
    : `Edit "${ escapeHTML(credential.displayName || credential.name) }"`;

  const form = domify(
    `<div class="ci-form">
      <h5>${ heading }</h5>
      ${ isUpgrade ? `<p class="ci-upgrade-reason">This credential is based on template v${ credential.credentialTemplateVersion }; this connector requires v${ floor } or later. Fill in the new fields below.</p>` : '' }
      <div class="ci-form-row">
        <label>Credential ID <span style="font-size:11px;color:#888;">(immutable)</span></label>
        <input type="text" value="${ escapeHTML(credential.name) }" disabled />
      </div>
      <div class="ci-form-row">
        <label>Display name</label>
        <input type="text" data-field="displayName" value="${ escapeHTML(credential.displayName || '') }" placeholder="e.g. Slack Production" />
      </div>
      <hr/>
      <p style="font-size:11px;color:#666;margin:4px 0 8px;">
        Credential template properties${ isUpgrade ? ' (existing values pre-filled; fill in any new fields)' : ''}
      </p>
      ${ matchingTemplate.properties.map(p => {
        const stored = (credential.storedValue && credential.storedValue[p.key]) || '';
        return `<div class="ci-form-row">
          <label>${ escapeHTML(p.label) }${ p.required ? ' *' : '' }${ p.secret ? ' 🔒' : '' }</label>
          <input type="${ p.secret ? 'password' : 'text' }" data-prop="${ escapeHTML(p.key) }" placeholder="${ p.secret ? 'camunda.secrets.MY_SECRET' : escapeHTML(p.key) }" value="${ escapeHTML(stored) }" />
          ${ p.secret ? '<span class="ci-field-warning" data-secret-warning="' + escapeHTML(p.key) + '"></span>' : '' }
        </div>`;
      }).join('') }
      <div class="ci-form-actions">
        <button data-primary data-action="save">${ isUpgrade ? 'Upgrade credential' : 'Save changes' }</button>
        <button data-action="cancel">Cancel</button>
      </div>
    </div>`
  );

  form.querySelector('[data-action="cancel"]').addEventListener('click', () => {
    formContainer.innerHTML = '';
  });

  form.querySelector('[data-action="save"]').addEventListener('click', () => {
    const displayName = form.querySelector('[data-field="displayName"]').value.trim();

    // On upgrade, bump version to floor; on edit, keep current version
    const newVersion = isUpgrade ? floor : credential.credentialTemplateVersion;

    // Collect the updated cluster-variable value from the template properties
    const storedValue = {};
    matchingTemplate.properties.forEach(p => {
      const input = form.querySelector(`[data-prop="${ p.key }"]`);
      if (input && input.value.trim() !== '') {
        storedValue[p.key] = input.value;
      }
    });

    const all = credentialInstances.getAll();
    const updated = [ ...all ];
    updated[idx] = {
      ...credential,
      displayName: displayName || credential.displayName || credential.name,
      credentialTemplateVersion: newVersion,
      version: newVersion,
      storedValue
    };

    credentialInstances.setInstances(updated);
    formContainer.innerHTML = '';
    rerender();
  });

  formContainer.appendChild(form);
}

function mountXmlViewer(bpmnjs, container) {
  const xmlBtn = domify('<button class="ci-toggle-btn" style="left: 120px;">&#60;/&#62; XML</button>');
  container.appendChild(xmlBtn);

  xmlBtn.addEventListener('click', async () => {
    const { xml } = await bpmnjs.saveXML({ format: true });

    const backdrop = domify('<div class="xml-modal-backdrop"></div>');
    const modal = domify(
      `<div class="xml-modal">
        <div class="xml-modal-header">
          <h3>BPMN XML</h3>
          <button data-close>&times;</button>
        </div>
        <pre></pre>
      </div>`
    );

    modal.querySelector('pre').textContent = xml;
    modal.querySelector('[data-close]').addEventListener('click', () => backdrop.remove());
    backdrop.addEventListener('click', (e) => { if (e.target === backdrop) backdrop.remove(); });

    backdrop.appendChild(modal);
    document.body.appendChild(backdrop);
  });
}
